-- generated by cmd/gen-seed — do not edit by hand

DELETE FROM recipe_ingredients;
DELETE FROM recipes;
DELETE FROM ingredient_tags;
DELETE FROM ingredients;
DELETE FROM food_tags WHERE slug IN ('gluten', 'crustaceans', 'eggs', 'fish', 'peanuts', 'soybeans', 'milk', 'nuts', 'celery', 'mustard', 'sesame', 'sulphites', 'lupin', 'molluscs', 'vegetarian', 'vegan');
